House Price Pridiction

In [46]:
import numpy as np 
import pandas as pd

#data read

In [3]:
df = pd.read_csv(r"C:\Users\Dell Latitude 5480\Downloads\archive (3).zip")

In [4]:
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

#Information

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

#Head

In [6]:
df.head(3)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746

#Tail

In [7]:
df.tail(3)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

#Sample

In [8]:
df.sample(2)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
1848,1849,2690,3,1,1,1925,Suburban,Good,No,550884
51,52,2085,2,3,2,1935,Urban,Poor,Yes,405446

#Columns

In [9]:
df.columns

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='object')

#Shape

In [10]:
df.shape

(2000, 10)

#Data Type

In [11]:
df.dtypes

Id            int64
Area          int64
Bedrooms      int64
Bathrooms     int64
Floors        int64
YearBuilt     int64
Location     object
Condition    object
Garage       object
Price         int64
dtype: object

#Describe

In [45]:
df.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

#Location

In [13]:
df.loc[0]

Id                   1
Area              1360
Bedrooms             5
Bathrooms            4
Floors               3
YearBuilt         1970
Location      Downtown
Condition    Excellent
Garage              No
Price           149919
Name: 0, dtype: object

In [ ]:
#

In [14]:
df.iloc[0]

Id                   1
Area              1360
Bedrooms             5
Bathrooms            4
Floors               3
YearBuilt         1970
Location      Downtown
Condition    Excellent
Garage              No
Price           149919
Name: 0, dtype: object

In [44]:
df.isnull()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False
1997,False,False,False,False,False,False,False,False,False,False
1998,False,False,False,False,False,False,False,False,False,False
1999,False,False,False,False,False,False,False,False,False,False

In [47]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [17]:
df["Condition"].unique()

array(['Excellent', 'Good', 'Fair', 'Poor'], dtype=object)

In [18]:
df["Condition"].nunique()

4

In [19]:
df["Location"].value_counts()

Location
Downtown    558
Urban       485
Suburban    483
Rural       474
Name: count, dtype: int64

In [20]:
df["Location"].value_counts().sort_values()

Location
Rural       474
Suburban    483
Urban       485
Downtown    558
Name: count, dtype: int64

In [21]:
df["Location"].value_counts().sort_values(ascending =False)

Location
Downtown    558
Urban       485
Suburban    483
Rural       474
Name: count, dtype: int64

In [22]:
df.sort_values("Location")

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1337,1338,3593,2,2,3,1951,Downtown,Fair,No,720534
494,495,4768,4,4,2,1986,Downtown,Fair,No,596120
496,497,4209,1,4,2,2020,Downtown,Poor,Yes,346784
1330,1331,1386,3,3,1,1938,Downtown,Good,Yes,380918
...,...,...,...,...,...,...,...,...,...,...
1122,1123,4997,2,2,2,1918,Urban,Excellent,No,286887
650,651,3093,1,4,1,1906,Urban,Poor,Yes,415863
1120,1121,1434,1,4,1,2003,Urban,Good,Yes,210353
1573,1574,1468,2,2,1,1974,Urban,Excellent,Yes,957107
833,834,3728,5,1,3,2007,Urban,Poor,No,178145

In [23]:
df.sort_values(["Location","Floors"])

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
9,10,2185,3,3,1,2000,Downtown,Poor,No,340375
17,18,974,2,2,1,1919,Downtown,Poor,Yes,905742
21,22,3247,4,3,1,1931,Downtown,Excellent,No,709789
22,23,1475,3,1,1,1927,Downtown,Poor,No,709966
27,28,2399,2,4,1,1934,Downtown,Excellent,Yes,513179
...,...,...,...,...,...,...,...,...,...,...
1971,1972,3349,1,3,3,1900,Urban,Excellent,Yes,953785
1982,1983,4682,3,3,3,1961,Urban,Excellent,No,597685
1986,1987,3211,4,3,3,1965,Urban,Good,No,179576
1987,1988,3588,4,1,3,1929,Urban,Poor,No,59765
1992,1993,2450,1,3,3,2006,Urban,Good,Yes,225508

In [24]:
df.drop_duplicates(subset=["Location"])

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
5,6,3944,1,2,1,1906,Urban,Poor,No,93262
6,7,3671,1,1,2,1948,Rural,Poor,Yes,448722

In [25]:
df.rename (columns={"YearBuilt" : "Year"})

,Id,Area,Bedrooms,Bathrooms,Floors,Year,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [26]:
df.rename (index= {0:"first_entry" ,1 :"second_entry"})

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
first_entry,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
second_entry,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [27]:
Locations = df.groupby("Location")

In [28]:
Locations

In [29]:
len(df)

2000

In [30]:
len(Locations)

4

In [31]:
Locations.size()

Location
Downtown    558
Rural       474
Suburban    483
Urban       485
dtype: int64

In [32]:
Locations.first()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Condition,Garage,Price
Location,,,,,,,,,
Downtown,1,1360,5,4,3,1970,Excellent,No,149919
Rural,7,3671,1,1,2,1948,Poor,Yes,448722
Suburban,4,966,4,2,2,1902,Fair,Yes,244020
Urban,6,3944,1,2,1,1906,Poor,No,93262

In [33]:
df1 = pd.read_csv(r"C:\Users\Dell Latitude 5480\Downloads\patients.csv")

In [34]:
df1

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [35]:
df2 = pd.read_csv(r"C:\Users\Dell Latitude 5480\Downloads\treatments_cut.csv")

In [36]:
df2

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.95
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,NaN
69,armina,sauvé,36u - 46u,-,7.86,7.40,NaN

In [38]:
df.join(df1)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,...,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919,...,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66.0,19.6
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998,...,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66.0,19.2
2,3,3592,2,2,3,1938,Downtown,Good,No,266746,...,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71.0,24.8
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020,...,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70.0,31.7
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056,...,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27.0,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
pd.concat([df,df1])

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,...,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1.0,1360.0,5.0,4.0,3.0,1970.0,Downtown,Excellent,No,149919.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,4272.0,5.0,4.0,3.0,1958.0,Downtown,Excellent,No,424998.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,3592.0,2.0,2.0,3.0,1938.0,Downtown,Good,No,266746.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,966.0,4.0,2.0,2.0,1902.0,Suburban,Fair,Yes,244020.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,4926.0,1.0,4.0,2.0,1975.0,Downtown,Fair,Yes,636056.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72.0,24.6
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70.0,34.4
500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67.0,26.8
501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67.0,27.7
502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71.0,19.3