In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dell latitude 5480\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell latitude 5480\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell latitude 5480\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell latitude 5480\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell latitude 5480\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell latitude 5480\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
#series 
#dataframe
#panel

In [4]:
series1 = pd.Series([10,20,30])
print(series1)

0    10
1    20
2    30
dtype: int64

In [5]:
series2 = pd.Series(["Kavi","Shyam","Ravi"],index=[1,2,3])
print(series2)

1     Kavi
2    Shyam
3     Ravi
dtype: object

#Creation of series from numpy arrays

In [6]:
import numpy as np 
import pandas as pd

In [7]:
array1 = np.array([1,2,3,4])
series = pd.Series(array1)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
series4 = pd.Series(array1 , index =["Jan","Feb","March","April"])
print(series4)

Jan      1
Feb      2
March    3
April    4
dtype: int64

#Creation of series from dictionary

In [10]:
dict1 = {"Delhi" : "NewDelhi",
         "Uk" : "London",
         "Japan": "Tokyo"}
print(dict1)

{'Delhi': 'NewDelhi', 'Uk': 'London', 'Japan': 'Tokyo'}

In [11]:
series5 = pd.Series(dict1)
print(series5)

Delhi    NewDelhi
Uk         London
Japan       Tokyo
dtype: object

#Accessing element of a series

In [12]:
import pandas as pd

In [13]:
seriesnum = pd.Series([10,20,30])
print(seriesnum)

0    10
1    20
2    30
dtype: int64

In [14]:
seriesmonth = pd.Series([1,2,3],index=["Jan","Feb","March"])
seriesmonth["March"]

np.int64(3)

In [15]:
seriesmonth["Feb"]

np.int64(2)

In [16]:
seriesmonth["Jan"]

np.int64(1)

In [17]:
seriesnum[2]

np.int64(30)

In [18]:
seriesnum[1]

np.int64(20)

In [19]:
seriesnum[0]

np.int64(10)

#Slicing

In [20]:
seriescountry =pd.Series(["NewDelhi" ,"WashingtonDC","London","Paris"],index=["India","USA","UK","France"])
print(seriescountry)

India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
dtype: object

In [21]:
seriescountry[1:3]

USA    WashingtonDC
UK           London
dtype: object

In [22]:
seriescountry[0:]

India         NewDelhi
USA       WashingtonDC
UK              London
France           Paris
dtype: object

#Methods of series

In [23]:
import pandas as pd

In [24]:
seriestentwenty =pd.Series(np.arange(10,20,1))
seriestentwenty

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [25]:
seriestentwenty.head(2)

0    10
1    11
dtype: int64

In [26]:
seriestentwenty.tail(2)

8    18
9    19
dtype: int64

In [27]:
seriestentwenty.count()

np.int64(10)

#Mathematical operations on series

In [28]:
seriesA = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
seriesA

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [29]:
seriesB= pd.Series([10,20,-10,50,100],index=["z","y","a","c","e"])
seriesB

z     10
y     20
a    -10
c     50
e    100
dtype: int64

#Addition

In [30]:
seriesA+seriesB

a     -9.0
b      NaN
c     53.0
d      NaN
e    105.0
y      NaN
z      NaN
dtype: float64

#Subtraction

In [31]:
seriesA-seriesB

a    11.0
b     NaN
c   -47.0
d     NaN
e   -95.0
y     NaN
z     NaN
dtype: float64

#Multiplication

In [32]:
seriesA*seriesB

a    -10.0
b      NaN
c    150.0
d      NaN
e    500.0
y      NaN
z      NaN
dtype: float64

#Division

In [33]:
seriesA/seriesB

a   -0.10
b     NaN
c    0.06
d     NaN
e    0.05
y     NaN
z     NaN
dtype: float64

#Dataframe

In [34]:
import numpy as np
import pandas as pd

In [35]:
dframe = pd.DataFrame([1,2,3,4])
print(dframe)

   0
0  1
1  2
2  3
3  4

In [36]:
array1 = np.array([10,20,30,40])
dframe = pd.DataFrame(array1)
print(dframe)

    0
0  10
1  20
2  30
3  40

In [37]:
listdict1 =({"a":5,"b":10},{"a":5,"b":10,"c":15})
dframelist1 = pd.DataFrame(listdict1)
print(dframelist1)

   a   b     c
0  5  10   NaN
1  5  10  15.0

In [38]:
listdict = ({"a":10,"b":20},{"a":5,"b":10,"c":20})
dframelist = pd.DataFrame(listdict)
print(dframelist)

    a   b     c
0  10  20   NaN
1   5  10  20.0

In [39]:
seriesA = pd.Series([1,2,3,4,5],index = ['a', 'b', 'c', 'd', 'e'])
seriesB = pd.Series ([1000,2000,-1000,-5000,1000],index = ['a', 'b', 'c', 'd', 'e'])
seriesC = pd.Series([10,20,-10,-50,100],index = ['z', 'y', 'a', 'c', 'e'])

dFrame6 = pd.DataFrame(seriesA)
dFrame6

   0
a  1
b  2
c  3
d  4
e  5

In [40]:
dframe7 = pd.DataFrame([seriesA,seriesB])
dframe7

      a     b     c     d     e
0     1     2     3     4     5
1  1000  2000 -1000 -5000  1000

In [41]:
dframe8 = pd.DataFrame([seriesA,seriesC])
print(dframe8)

      a    b     c    d      e     z     y
0   1.0  2.0   3.0  4.0    5.0   NaN   NaN
1 -10.0  NaN -50.0  NaN  100.0  10.0  20.0

In [42]:
ResultSheet={'Arnab': pd.Series([90, 91, 97],index=['Maths','Science','Hindi']),
'Ramit': pd.Series([92, 81, 96],index=['Maths','Science','Hindi']),
'Sahir': pd.Series([89, 91, 88],index=['Maths','Science','Hindi']),
'Riya': pd.Series([81, 71, 67],index=['Maths','Science','Hindi']),
'Mallika': pd.Series([94, 95, 99],index=['Maths','Science','Hindi'])}
ResultDF = pd.DataFrame(ResultSheet)
ResultDF

         Arnab  Ramit  Sahir  Riya  Mallika
Maths       90     92     89    81       94
Science     91     81     91    71       95
Hindi       97     96     88    67       99

In [43]:
#Adding a new column to a DataFrame

In [44]:
ResultDF['Jimmy']=[89,78,76]
ResultDF

         Arnab  Ramit  Sahir  Riya  Mallika  Jimmy
Maths       90     92     89    81       94     89
Science     91     81     91    71       95     78
Hindi       97     96     88    67       99     76

In [45]:
ResultDF = ResultDF.drop('Science', axis=0)
ResultDF

       Arnab  Ramit  Sahir  Riya  Mallika  Jimmy
Maths     90     92     89    81       94     89
Hindi     97     96     88    67       99     76

In [46]:
ResultDF = ResultDF.drop(['Ramit','Riya'], axis=1)
ResultDF

       Arnab  Sahir  Mallika  Jimmy
Maths     90     89       94     89
Hindi     97     88       99     76

In [47]:
ResultDF=ResultDF.rename({'Maths':'Sub1','English':'Sub3','Hindi':'Sub4'}, axis='index')
print(ResultDF)

      Arnab  Sahir  Mallika  Jimmy
Sub1     90     89       94     89
Sub4     97     88       99     76

In [48]:
ResultDF.loc['Sub1': 'Sub4']

      Arnab  Sahir  Mallika  Jimmy
Sub1     90     89       94     89
Sub4     97     88       99     76