Global Air Pollution

In [1]:
import numpy as np 
import pandas as pd

#Data Read

In [2]:
df = pd.read_csv(r"C:\Users\Dell Latitude 5480\Downloads\archive (1).zip")

In [3]:
df

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
1,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy
3,2025-11-08 03:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,73.6,72.8,11.8,863.0,20.0,0.19,Unhealthy
4,2025-11-08 04:00:00,"Lahore, Pakistan",31.5497,74.3436,69.8,71.2,57.7,11.1,811.0,31.0,0.19,Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...
17467,2026-02-06 19:00:00,"Jakarta, Indonesia",-6.2088,106.8456,49.4,49.9,48.6,39.2,3014.0,5.0,0.16,Unhealthy for Sensitive
17468,2026-02-06 20:00:00,"Jakarta, Indonesia",-6.2088,106.8456,59.6,60.5,47.3,41.6,2791.0,1.0,0.15,Unhealthy
17469,2026-02-06 21:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,41.5,42.5,2200.0,1.0,0.16,Unhealthy
17470,2026-02-06 22:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,36.0,42.0,1672.0,1.0,0.16,Unhealthy
17471,2026-02-06 23:00:00,"Jakarta, Indonesia",-6.2088,106.8456,60.1,60.8,32.2,39.7,1343.0,1.0,0.17,Unhealthy

#Head

In [4]:
df.head(3)

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
1,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy

#Tail

In [5]:
df.tail(3)

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
17469,2026-02-06 21:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,41.5,42.5,2200.0,1.0,0.16,Unhealthy
17470,2026-02-06 22:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,36.0,42.0,1672.0,1.0,0.16,Unhealthy
17471,2026-02-06 23:00:00,"Jakarta, Indonesia",-6.2088,106.8456,60.1,60.8,32.2,39.7,1343.0,1.0,0.17,Unhealthy

#Sample

In [6]:
df.sample(3)

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
15952,2025-12-05 16:00:00,"Jakarta, Indonesia",-6.2088,106.8456,47.6,47.6,30.4,45.8,1554.0,181.0,0.71,Unhealthy for Sensitive
1442,2026-01-07 02:00:00,"Lahore, Pakistan",31.5497,74.3436,178.3,184.4,75.7,23.6,2501.0,14.0,0.63,Hazardous
6925,2025-11-23 13:00:00,"New York, USA",40.7128,-74.0060,13.6,13.7,52.5,12.5,273.0,22.0,0.19,Moderate

#Information

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17472 entries, 0 to 17471
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   17472 non-null  object
 1   City                   17472 non-null  object
 2   Latitude               17472 non-null  float64
 3   Longitude              17472 non-null  float64
 4   PM2.5                  17472 non-null  float64
 5   PM10                   17472 non-null  float64
 6   NO2                    17472 non-null  float64
 7   SO2                    17472 non-null  float64
 8   CO                     17472 non-null  float64
 9   Ozone                  17472 non-null  float64
 10  Aerosol_Optical_Depth  17472 non-null  float64
 11  AQI_Class              17472 non-null  object
dtypes: float64(9), object(3)
memory usage: 1.6+ MB

#Describe

In [8]:
df.describe()

,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth
count,17472.000000,17472.000000,17472.000000,17472.000000,17472.000000,17472.000000,17472.000000,17472.000000,17472.000000
mean,23.292375,43.056375,66.060611,69.263124,38.458871,30.292691,1264.659741,54.746337,0.325342
std,23.814690,68.421659,65.414505,66.576392,26.977070,41.777128,1484.401277,49.928268,0.255573
min,-23.550500,-74.006000,0.300000,0.400000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,16.305525,-11.754175,13.175000,14.800000,17.700000,6.100000,278.000000,16.000000,0.120000
50%,30.081800,75.776300,45.500000,48.900000,31.800000,14.400000,713.000000,45.000000,0.270000
75%,40.106350,94.520775,99.700000,104.300000,53.600000,37.900000,1627.000000,71.000000,0.470000
max,51.507400,116.407400,430.300000,434.000000,185.100000,439.300000,13039.000000,288.000000,2.980000

#Columns

In [9]:
df.columns

Index(['Date', 'City', 'Latitude', 'Longitude', 'PM2.5', 'PM10', 'NO2', 'SO2',
       'CO', 'Ozone', 'Aerosol_Optical_Depth', 'AQI_Class'],
      dtype='object')

#Shape

In [21]:
df.shape

(17472, 12)

#Data Type

In [10]:
df.dtypes

Date                      object
City                      object
Latitude                 float64
Longitude                float64
PM2.5                    float64
PM10                     float64
NO2                      float64
SO2                      float64
CO                       float64
Ozone                    float64
Aerosol_Optical_Depth    float64
AQI_Class                 object
dtype: object

#Location

In [11]:
df.loc[1]

Date                     2025-11-08 01:00:00
City                        Lahore, Pakistan
Latitude                             31.5497
Longitude                            74.3436
PM2.5                                   78.2
PM10                                    79.6
NO2                                     90.9
SO2                                     14.4
CO                                    1413.0
Ozone                                   10.0
Aerosol_Optical_Depth                   0.19
AQI_Class                          Unhealthy
Name: 1, dtype: object

In [12]:
df.iloc[1]

Date                     2025-11-08 01:00:00
City                        Lahore, Pakistan
Latitude                             31.5497
Longitude                            74.3436
PM2.5                                   78.2
PM10                                    79.6
NO2                                     90.9
SO2                                     14.4
CO                                    1413.0
Ozone                                   10.0
Aerosol_Optical_Depth                   0.19
AQI_Class                          Unhealthy
Name: 1, dtype: object

#Null

In [13]:
df.isnull()

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
17467,False,False,False,False,False,False,False,False,False,False,False,False
17468,False,False,False,False,False,False,False,False,False,False,False,False
17469,False,False,False,False,False,False,False,False,False,False,False,False
17470,False,False,False,False,False,False,False,False,False,False,False,False
17471,False,False,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

Date                     0
City                     0
Latitude                 0
Longitude                0
PM2.5                    0
PM10                     0
NO2                      0
SO2                      0
CO                       0
Ozone                    0
Aerosol_Optical_Depth    0
AQI_Class                0
dtype: int64

#Unique

In [17]:
df["AQI_Class"].unique()

array(['Unhealthy', 'Unhealthy for Sensitive', 'Moderate', 'Hazardous',
       'Good'], dtype=object)

In [18]:
df["AQI_Class"].nunique()

5

#Value count

In [24]:
df["AQI_Class"].value_counts()

AQI_Class
Unhealthy                  5970
Good                       4032
Moderate                   3829
Hazardous                  1991
Unhealthy for Sensitive    1650
Name: count, dtype: int64

In [25]:
df["AQI_Class"].value_counts().sort_values()

AQI_Class
Unhealthy for Sensitive    1650
Hazardous                  1991
Moderate                   3829
Good                       4032
Unhealthy                  5970
Name: count, dtype: int64

In [26]:
df["AQI_Class"].value_counts().sort_values(ascending = False)

AQI_Class
Unhealthy                  5970
Good                       4032
Moderate                   3829
Hazardous                  1991
Unhealthy for Sensitive    1650
Name: count, dtype: int64

In [28]:
df.sort_values("AQI_Class")

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
13373,2025-11-19 05:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,5.2,5.2,9.5,4.5,239.0,47.0,0.10,Good
7034,2025-11-28 02:00:00,"New York, USA",40.7128,-74.0060,4.3,4.3,11.7,6.8,185.0,52.0,0.04,Good
7033,2025-11-28 01:00:00,"New York, USA",40.7128,-74.0060,4.9,4.9,13.5,7.4,191.0,50.0,0.05,Good
7032,2025-11-28 00:00:00,"New York, USA",40.7128,-74.0060,5.7,5.7,16.0,7.8,198.0,48.0,0.05,Good
7031,2025-11-27 23:00:00,"New York, USA",40.7128,-74.0060,6.8,6.9,19.1,8.1,207.0,45.0,0.06,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
2966,2025-12-10 14:00:00,"Delhi, India",28.6139,77.2090,43.5,44.2,10.7,36.0,969.0,164.0,0.25,Unhealthy for Sensitive
2965,2025-12-10 13:00:00,"Delhi, India",28.6139,77.2090,45.5,46.3,8.3,36.2,1004.0,167.0,0.23,Unhealthy for Sensitive
2964,2025-12-10 12:00:00,"Delhi, India",28.6139,77.2090,50.5,51.2,12.0,37.4,1110.0,159.0,0.21,Unhealthy for Sensitive
2992,2025-12-11 16:00:00,"Delhi, India",28.6139,77.2090,49.4,49.8,38.9,44.0,858.0,116.0,0.27,Unhealthy for Sensitive
8735,2026-02-06 23:00:00,"New York, USA",40.7128,-74.0060,41.6,42.0,82.5,10.9,560.0,1.0,0.25,Unhealthy for Sensitive

In [29]:
df.sort_values(["AQI_Class","City"])

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
4565,2025-11-16 05:00:00,"Beijing, China",39.9042,116.4074,12.0,35.5,7.1,7.9,225.0,61.0,0.09,Good
4566,2025-11-16 06:00:00,"Beijing, China",39.9042,116.4074,8.4,14.4,11.8,9.7,369.0,55.0,0.05,Good
4571,2025-11-16 11:00:00,"Beijing, China",39.9042,116.4074,11.7,27.1,8.8,9.7,312.0,55.0,0.07,Good
4572,2025-11-16 12:00:00,"Beijing, China",39.9042,116.4074,10.6,26.4,6.8,8.6,267.0,58.0,0.08,Good
4573,2025-11-16 13:00:00,"Beijing, China",39.9042,116.4074,9.2,21.2,6.4,7.7,259.0,59.0,0.08,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
15053,2026-01-28 05:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,39.6,39.6,35.3,11.0,469.0,19.0,0.25,Unhealthy for Sensitive
15054,2026-01-28 06:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,38.3,38.3,33.0,11.2,457.0,26.0,0.24,Unhealthy for Sensitive
15055,2026-01-28 07:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,36.9,36.9,27.0,11.8,443.0,57.0,0.22,Unhealthy for Sensitive
15092,2026-01-29 20:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,35.2,35.2,38.1,13.6,596.0,87.0,0.37,Unhealthy for Sensitive
15141,2026-01-31 21:00:00,"Sao Paulo, Brazil",-23.5505,-46.6333,37.0,37.3,53.3,15.1,852.0,49.0,0.29,Unhealthy for Sensitive

In [30]:
df.drop_duplicates(subset=["AQI_Class"])

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
10,2025-11-08 10:00:00,"Lahore, Pakistan",31.5497,74.3436,53.7,55.3,29.2,18.7,2540.0,116.0,0.20,Unhealthy for Sensitive
11,2025-11-08 11:00:00,"Lahore, Pakistan",31.5497,74.3436,29.3,31.0,14.8,20.4,1624.0,153.0,0.21,Moderate
127,2025-11-13 07:00:00,"Lahore, Pakistan",31.5497,74.3436,156.5,160.2,80.3,21.8,4634.0,10.0,0.31,Hazardous
4565,2025-11-16 05:00:00,"Beijing, China",39.9042,116.4074,12.0,35.5,7.1,7.9,225.0,61.0,0.09,Good

In [35]:
df.rename ( columns = {"City" : "State"})

,Date,State,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
1,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy
3,2025-11-08 03:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,73.6,72.8,11.8,863.0,20.0,0.19,Unhealthy
4,2025-11-08 04:00:00,"Lahore, Pakistan",31.5497,74.3436,69.8,71.2,57.7,11.1,811.0,31.0,0.19,Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...
17467,2026-02-06 19:00:00,"Jakarta, Indonesia",-6.2088,106.8456,49.4,49.9,48.6,39.2,3014.0,5.0,0.16,Unhealthy for Sensitive
17468,2026-02-06 20:00:00,"Jakarta, Indonesia",-6.2088,106.8456,59.6,60.5,47.3,41.6,2791.0,1.0,0.15,Unhealthy
17469,2026-02-06 21:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,41.5,42.5,2200.0,1.0,0.16,Unhealthy
17470,2026-02-06 22:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,36.0,42.0,1672.0,1.0,0.16,Unhealthy
17471,2026-02-06 23:00:00,"Jakarta, Indonesia",-6.2088,106.8456,60.1,60.8,32.2,39.7,1343.0,1.0,0.17,Unhealthy

In [36]:
df .rename ( index ={0 : "First" , 1 : "Second"})

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
First,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
Second,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy
3,2025-11-08 03:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,73.6,72.8,11.8,863.0,20.0,0.19,Unhealthy
4,2025-11-08 04:00:00,"Lahore, Pakistan",31.5497,74.3436,69.8,71.2,57.7,11.1,811.0,31.0,0.19,Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...
17467,2026-02-06 19:00:00,"Jakarta, Indonesia",-6.2088,106.8456,49.4,49.9,48.6,39.2,3014.0,5.0,0.16,Unhealthy for Sensitive
17468,2026-02-06 20:00:00,"Jakarta, Indonesia",-6.2088,106.8456,59.6,60.5,47.3,41.6,2791.0,1.0,0.15,Unhealthy
17469,2026-02-06 21:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,41.5,42.5,2200.0,1.0,0.16,Unhealthy
17470,2026-02-06 22:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,36.0,42.0,1672.0,1.0,0.16,Unhealthy
17471,2026-02-06 23:00:00,"Jakarta, Indonesia",-6.2088,106.8456,60.1,60.8,32.2,39.7,1343.0,1.0,0.17,Unhealthy

In [39]:
cities = df.groupby("City")

In [40]:
cities

In [42]:
len(df)

17472

In [43]:
len(cities)

8

In [44]:
cities.size()

City
Beijing, China        2184
Delhi, India          2184
Dhaka, Bangladesh     2184
Jakarta, Indonesia    2184
Lahore, Pakistan      2184
London, UK            2184
New York, USA         2184
Sao Paulo, Brazil     2184
dtype: int64

In [45]:
cities.first()

,Date,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
City,,,,,,,,,,,
"Beijing, China",2025-11-08 00:00:00,39.9042,116.4074,96.9,99.9,55.4,72.7,2884.0,0.0,0.56,Unhealthy
"Delhi, India",2025-11-08 00:00:00,28.6139,77.2090,50.5,149.9,23.9,14.6,513.0,69.0,0.24,Unhealthy for Sensitive
"Dhaka, Bangladesh",2025-11-08 00:00:00,23.8103,90.4125,48.5,49.2,18.9,5.5,630.0,63.0,0.36,Unhealthy for Sensitive
"Jakarta, Indonesia",2025-11-08 00:00:00,-6.2088,106.8456,53.9,54.5,34.8,41.6,570.0,4.0,0.28,Unhealthy for Sensitive
"Lahore, Pakistan",2025-11-08 00:00:00,31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
"London, UK",2025-11-08 00:00:00,51.5074,-0.1278,4.6,7.1,21.4,1.9,142.0,46.0,0.09,Good
"New York, USA",2025-11-08 00:00:00,40.7128,-74.0060,5.8,5.9,16.3,4.7,180.0,73.0,0.19,Good
"Sao Paulo, Brazil",2025-11-08 00:00:00,-23.5505,-46.6333,24.8,25.8,55.3,14.7,365.0,26.0,0.22,Moderate